### ISSUE TITLE
Script upload issue.

### ISSUE THREAD

**Issue by dougkoellmer** [iDevicesInc/SweetBlue#104]
```
Total time: 1 mins 39.39 secs
Are you sure you want to upload? y
********************UPLOADING ZIPS TO SERVER********************

sweetblue_.zip: No such file or directory
Killed by signal 1.`
```

NOTE: I pressed 'y' then Enter really quick because that's what I'm used to (as opposed to y being automatically accepted). Not sure if that has anything to do with it.

**Comment by ryanidev** [comment]
This should be fixed now. It wasn't pulling the version correctly (so it couldn't find the file properly). I also had to have it copy the sweetblue.zip to sweetblue_{version}.zip, which wasn't happening before.
