### ISSUE TITLE
ScanFilters not removed

### ISSUE THREAD

**Issue by martinbrylski** [iDevicesInc/SweetBlue#126]
In `startScan()` and `startPeriodicScan()` a `ScanFilter` can be provided, that filters out devices for the `DiscoveryListener`.

There is a `stopScan()` method in which an old `ScanFilter` is removed from the filter manager. On `stopPeriodicScan()` and other methods the filters are not removed. So stopping a periodic scan, will never remove a scan filter.

Is this intended? Should not there only be one scanfilter associated with a specific devicelistener. And as the devicelistener is removed, scan stopped, ..., the filter should also be removed?

PS:
Sorry for messing up the issues page

**Comment by dougkoellmer** [comment]
I added an overload to stopPeriodicScan() in 624f7ce7335ebcd6ebca096fc7a4c18ca91b93c4 that will also remove the filter for you. Thanks!
