### ISSUE TITLE
Notification Callback

### ISSUE THREAD

**Issue by shashank090789** [iDevicesInc/SweetBlue#127]
How to get callback of characteristic change just like BluetoothGattCallback.
I have to  sync 30 days data from pedometer and for each date their is specific write command after 
that pedometer gives the response for each day and onCharacteristicRead is called from BluetoothGattCallback. How would I use this library for the same

**Comment by dougkoellmer** [comment]
```java
device.enableNotify(UUID_IN, new ReadWriteListener()
{
    @Override public void onEvent(ReadWriteEvent e)
    {
        if( e.wasSuccess() )
        {
            device.write(UUID_OUT, mData);
        }
    }
}
```

**Comment by dougkoellmer** [comment]
Updated the code sample a bit to be more specific.

**Comment by shashank090789** [comment]
thanks, it's working now
