### ISSUE TITLE
How to retry 

### ISSUE THREAD

**Issue by shashank090789** [iDevicesInc/SweetBlue#129]
How to retry if DISCOVERING_SERVICES_FAILED

**Comment by dougkoellmer** [comment]
By default SweetBlue will try connecting again 2-3 more times using [DefaultConnectionFailListener](http://idevicesinc.com/sweetblue/docs/api/com/idevicesinc/sweetblue/BleDevice.DefaultConnectionFailListener.html). If all attempts fail consistently then you may have a problem with your firmware, or you may need to restart your phone.

See more troubleshooting steps see here:
https://github.com/iDevicesInc/SweetBlue/wiki/Troubleshooting
