### ISSUE TITLE
BleServer : onCharacteristicWriteRequest's value is not send back in BleServer.IncomingListener.IncomingEvent

### ISSUE THREAD

**Issue by c10h22** [iDevicesInc/SweetBlue#134]
Hi,

I am testing BleServer capabilities of SweetBlue and I noticed that there is no way to get the value that was written by a peripheral on a specific characteristic.

With BleGattServer, we typically use onCharacteristicWriteRequest parameter "byte[] value" to check the value written. When looking to P_BleServer_Listener we noticed that the value is not send back to BleServer.IncomingListener.IncomingEvent. The value that is always send back is BleServer.EMPTY_BYTE_ARRAY

Is there any way to get this value?

Regards,
Adnene

**Comment by dougkoellmer** [comment]
Doh, sorry, copy/paste typo, should be fixed now.
