### ISSUE TITLE
Main build script doesn't seem to upload API docs to server.

### ISSUE THREAD

**Issue by dougkoellmer** [iDevicesInc/SweetBlue#142]
Running build_then_upload_docs.sh works but it doesn't seem like build_release_bundle_then_upload.sh works.

**Comment by ryanidev** [comment]
Could you give a little more info on what doesn't work with build_release_bundle_then_upload.sh?

**Comment by dougkoellmer** [comment]
Don't have any details besides that I've confirmed build_then_upload_docs.sh uploads new files to idevicesinc.com/sweetblue/api/docs, and build_release_bundle_then_upload.sh does not.

**Comment by ryanidev** [comment]
Ok, so you were referring to the actual uploading process.

**Comment by ryanidev** [comment]
Updated build scripts to upload docs as well as zip files to server. Also added a check in case ssh key is not valid.
