### ISSUE TITLE
Cordova Support

### ISSUE THREAD

**Issue by dested** [iDevicesInc/SweetBlue#145]
Hey guys, is there any plans or intentions to wrap this library in a cordova plugin? Do you foresee any issues with doing that?

**Comment by dougkoellmer** [comment]
There are no technical problems with doing it. Of course getting it cross-platform would be a much bigger project, so it would only be for Android at first.

Realistically, business-wise it will probably require an Enterprise license to justify the cost of implementation in the immediate future. E-mail us at sweetblue@idevicesinc.com if you're interested in discussing it further.
