### ISSUE TITLE
PreLollipop Scan is stopped in Lollipop mode

### ISSUE THREAD

**Issue by bastiansch** [iDevicesInc/SweetBlue#204]
Hi

I have problems with scanning because of the hardcoded preLollipop mode. The scan is started here sweetblue_2_51_46-sources.jar!/com/idevicesinc/sweetblue/P_Task_Scan.java:228 preLollipop. The stopping of the scan is done here: sweetblue_2_51_46-sources.jar!/com/idevicesinc/sweetblue/BleManager.java:3114 the source code shows it uses the lollipop mode. this causes problems stopping the scan: "could not find callback wrapper" in android.bluetooth.le.BluetoothLeScanner#stopScan
what I do to start and stop the scan is: bleManager.startScan(Interval.secs(8.0), scanFilter);

**Comment by ryanidev** [comment]
Thanks for pointing that out, it will be fixed in the next release.
