### ISSUE TITLE
Infinite recursion in writeDescriptor

### ISSUE THREAD

**Issue by mgranberry** [iDevicesInc/SweetBlue#205]
The `public @Nullable(Prevalence.NEVER) ReadWriteListener.ReadWriteEvent writeDescriptor(final UUID characteristicUuid, final UUID descriptorUuid, final byte[] data, final ReadWriteListener listener)` overload infinitely calls itself.

**Comment by ryanidev** [comment]
So it does! Thanks for the report, it will be fixed in the next release.
