### ISSUE TITLE
Automatic Striping

### ISSUE THREAD

**Issue by stefreak** [iDevicesInc/SweetBlue#212]
Hi,

the README says SweetBlue supports "Automatic striping of characteristic writes greater than MTU size of 20 bytes."

I could not find any of this in your code or in examples, and just trying to pass a `byte[]` of larger than 20 bytes to `write()` just truncates the data.

So what does "automatic striping" do exactly and how to use it?

Best,
Steffen

**Comment by ryanidev** [comment]
You're right, it's not currently happening. I'll update the README for now to take that out for the moment. We are in the process of a major re-working of the library, so it will be taken care of in that.

**Comment by ryanidev** [comment]
This is in the current version now.
