### ISSUE TITLE
Disabling auto reconnection

### ISSUE THREAD

**Issue by kentcb** [iDevicesInc/SweetBlue#216]
Using 2.51.48: if I connect to a device, power it off, then turn it back on again, the device is automatically re-connected. Sounds like a good thing, but in the case of the particular app I'm writing, the client does not want this behavior.

I thought it would be pretty simple to fix: pass in a `ConnectionFailListener` that returns `DoNotRetry` from `OnEvent`. However, this is not working. My connection fail listener does not even get called.

How can I prevent auto-connection from occurring after a connection fails?

**Comment by ryanidev** [comment]
Create a ReconnectFilter, and set it in your BleManagerConfig. Just instantiate, and return Please.stopRetrying().

**Comment by kentcb** [comment]
Thanks @ryanidev. That does indeed appear to work. I'm still unsure why my original approach would not work, or what the `ConnectionFailListener` is supposed to do, though.

**Comment by idevbuilder** [comment]
The reconnect logic was added in an effort to make sure you can actually
connect to a device. Sometimes, a connect will just fail for no good
reason, and you simply have to retry. The ConnectionFailListener reports
after the retry logic has run it's course.
