### ISSUE TITLE
Handling indicate characteristics

### ISSUE THREAD

**Issue by kentcb** [iDevicesInc/SweetBlue#218]
Hi,

Does SweetBlue automatically handle characteristics that are marked as indicate? If not, how do I enable indicate on a characteristic? I can't find any docs on this.

**Comment by ryanidev** [comment]
Yes, SweetBlue automatically handles indications. They are treated the same (you still use enableNotify()). When trying to enable the characteristic, it checks if it's an indication, or notification, and takes the appropriate action.
