### ISSUE TITLE
Can't read a specific characteristic

### ISSUE THREAD

**Issue by nrbrook** [iDevicesInc/SweetBlue#222]
I have two battery characteristics with the same descriptors. The value of the descriptors identifies which characteristic is which. How can I read the second characteristic and its descriptor? All your APIs seem to be based on UUID and not on the specific attribute, only using the first characteristic for a specific UUID.

**Comment by ryanidev** [comment]
This is resolved as of 2.52.01 (you must use the DescriptorFilter to decide which Characteristic you want to read from).
