### ISSUE TITLE
Connection Failure History has no size limit checks

### ISSUE THREAD

**Issue by matkey** [iDevicesInc/SweetBlue#232]
http://idevicesinc.com/sweetblue/docs/api/com/idevicesinc/sweetblue/BleDevice.ConnectionFailListener.ConnectionFailEvent.html

The connection failure history (accessed via History) has not max size check. So if the device is out of range for a long period, then this connection history can get VERY big.
Needs a disable function to turn this off.

**Comment by ryanidev** [comment]
This will be in the next feature release (you will be able to set the max size of backing arraylist).

**Comment by ryanidev** [comment]
This is in as of 2.52.01
