### ISSUE TITLE
The autoConnect parameter is not used in Android >= 6.0

### ISSUE THREAD

**Issue by fabiorodella** [iDevicesInc/SweetBlue#238]
I noticed that even though I was setting the `alwaysUseAutoConnect` flag in my device config before connection, the logs always evidenced it being passed as `false` to the native call:
```
BluetoothGatt: connect() - device: 6C:EC:EB:45:99:97, auto: false
```

I started digging through the source code, and noticed that there's a separate GATT connection code path for Android >= 6.0 in `P_Task_Connect` (which seems to be used to set the transport parameter):
```
final boolean useAutoConnect = getDevice().shouldUseAutoConnect();

m_autoConnectUsage = useAutoConnect ? AutoConnectUsage.USED : AutoConnectUsage.NOT_USED;

if (Utils.isMarshmallow())
{
	m_gatt = M_Util.connect(getDevice().getNative(), getManager().getApplicationContext(), getDevice().getListeners());
}
else
{
...
```

The thing is that the `useAutoConnect` parameter is never passed into this method, and the native call is hardcoded to `false` inside `M_Util`. This was causing problems for the device I'm trying to connect to. I manually modified the library code to receive and use the parameter and now the reconnection behavior for this specific device is much better.

Was there a deeper reason for always using `false` for Marshmallow and up, or is it just an oversight? If it's the latter, I'll be glad to submit a PR with my change.

**Comment by ryanidev** [comment]
This is fixed in 2.52.01/02
