### ISSUE TITLE
startPeriodicScan not resuming after pause time

### ISSUE THREAD

**Issue by lukevr** [iDevicesInc/SweetBlue#240]
Hi,

could it be my fault that 

m_bleManager.startPeriodicScan(Interval.ONE_SEC,Interval.ONE_SEC,scanFilter, discoveryListener);

is not resuming scan after the first scanPauseTime? So it scans for 1 second and then stopes forever.

From other hand

m_bleManager.startScan(scanFilter, discoveryListener);

works fine.

**Comment by ryanidev** [comment]
What version is this on?

Also, you should consider scanning for longer than 1 second. That's not enough time to really find much, if anything, with a lot of android devices.
