### ISSUE TITLE
NPE on P_DeviceStateTracker.java line 55

### ISSUE THREAD

**Issue by ShaPOC** [iDevicesInc/SweetBlue#266]
Hello IDevicesInc!

Some listeners are already null check wrapped but this one isn't which causes an NPE in my project right now; [P_DeviceStateTracker.java#L55](https://github.com/iDevicesInc/SweetBlue/blob/master/app/src/main/java/com/idevicesinc/sweetblue/P_DeviceStateTracker.java#L55).

I'm using version 2.52.03 of SweetBlue.

A fix would be nice, thanks 👍

**Comment by ryanidev** [comment]
Fixed in 2.52.04
