### ISSUE TITLE
Null Pointer Exception in P_NativeServerWrapper.java

### ISSUE THREAD

**Issue by jrf121** [iDevicesInc/SweetBlue#313]
The following line in `SweetBlue/library/src/main/java/com/idevicesinc/sweetblue/P_NativeServerWrapper.java` will always produce a null pointer exception:
`75`    `if( !m_nativeLayer.isServerNull() )`

Similar unchecked references are made to the same member
`59`    `if( m_nativeLayer.isServerNull() )`
`184`    `if( m_nativeLayer.isServerNull() )`

This looks like it was introduced by @ryanidev in commit `65912f121bc23c09a4cf66ab622562597685c319`

**Comment by ryanidev** [comment]
Thanks for the report. It will be fixed in the coming release (2.52.09).
