### ISSUE TITLE
Scan Timoeut Listener

### ISSUE THREAD

**Issue by Petrulak** [iDevicesInc/SweetBlue#365]
Hello, is there a way how to detect Scan timeout?
Thank you

**Comment by ryanidev** [comment]
BleManager has a StateListener to can determine this with.

```
blemgr.setListener_State(new StateListener()
        {
            @Override
            public void onEvent(StateEvent e)
            {
                if (e.didExit(BleManagerState.SCANNING) && !mgr.isScanning())
                {
                     // Do what you want here.
                }
            }
        });
```

SweetBlue does periodic scans (unless you force an infiinte scan via the ScanOptions class when calling startScan()), so the isScanning check is to make sure that scanning is in fact stopped.

**Comment by Petrulak** [comment]
Amazing, thanks a lot @ryanidev !
