### ISSUE TITLE
small namespace issue in SweetBlue BleManager on ChangeIntent enum

### ISSUE THREAD

**Issue by clecoued** [iDevicesInc/SweetBlue#366]
Small issue when starting to include SweetBlue v2.52.10 library from sourceSet in my project.

At compilation time: 

----/----/app/src/main/lib/sweetblue/src/com/idevicesinc/sweetblue/BleManager.java
Error:(2992, 173) error: cannot find symbol variable ChangeIntent

```java
if( m_server != null )
{	
  m_server.disconnect_internal(BleServer.ServiceAddListener.Status.CANCELLED_FROM_BLE_TURNING_OFF, BleServer.ConnectionFailListener.Status.CANCELLED_FROM_BLE_TURNING_OFF, ChangeIntent.INTENTIONAL);
}
```

I fixed it by replacing ChangeIntent by State.ChangeIntent

**Comment by ryanidev** [comment]
Updated for the next release.
