### ISSUE TITLE
How to Change Pairing request timeout?

### ISSUE THREAD

**Issue by ka05** [iDevicesInc/SweetBlue#392]
When I connect to a device It appears that it only gives me about 15 seconds or less to enter the Pairing Key and then the dialog disappears and the Pairing request retries. Is the timeout configurable? If so how can i change it?

**Comment by ryanidev** [comment]
```
BleManagerConfig config = new BleManagerConfig();
config.taskTimeoutRequestFilter = new BleNodeConfig.DefaultTaskTimeoutRequestFilter() {
    @Override
    public Please onEvent(TaskTimeoutRequestEvent e)
    {
        if (e.task() == BleTask.BOND)
        {
            return Please.setTimeoutFor(Interval.secs(30));
        }
        return super.onEvent(e);
    }
};

BleManager mgr = BleManager.get(context, config);
```

Note that android seems to have a hard timeout for bonding/pairing of about 30 seconds, I haven't been able to get it to last longer than that in testing (though this may differ from device to device).
