### ISSUE TITLE
Bluetooth Passkey Example

### ISSUE THREAD

**Issue by barchard** [iDevicesInc/SweetBlue#406]
Hi, do you have any examples of pairing to a BlueTooth device with a PassKey? Thanks

**Comment by ryanidev** [comment]
Just call the bond() method in BleDevice.

**Comment by barchard** [comment]
thanks. I guess I wasn't completely clear. I was attempting to call set passkey on the raw BLE Device and disable passcode confirmation. I'm trying to pair and bond to a device programmatically for an internal project. no human intervention is desired. thanks.

**Comment by ryanidev** [comment]
In that case, you can get the native BluetoothDevice instance by calling BleDevice.getNative(). Then the method you want to use would be setPin (there's a hidden method call setPassKey, but looks like it's just stubbed out to do nothing).
