### ISSUE TITLE
[question] maintain long running connection

### ISSUE THREAD

**Issue by mbmc** [iDevicesInc/SweetBlue#409]
In Android O, it's no longer possible to have a service running indefinitely in the background. Also, `START_STICKY` doesn't guaranty a restart.

What would be your approach (aside from foreground service) to maintain a BLE connection between an Android phone and a device, where the Android phone is subscribing to notifications from the device. Also considering the app will be in the background and might not have UI at all.

**Comment by ryanidev** [comment]
A foreground service is probably the only real option, if you absolutely _must_ remain connected to the peripheral.

There may be another option out there, but I haven't looked into it all that much, as the apps I've been involved with don't require keeping the connection alive if the app is backgrounded (they just reconnect when they come back to the foreground).
