### ISSUE TITLE
Please provide some example how to use transactions

### ISSUE THREAD

**Issue by piupraidpiu** [iDevicesInc/SweetBlue#414]
Can't figure out how to use transaction. It totally not works at all for me.

**Comment by ryanidev** [comment]
What kind of transaction are you looking to use? Auth, Init, Ota?

**Comment by piupraidpiu** [comment]
Ota transactions. For example, I need to upload a firmware. It will be great if you can provide some example. Thank you.

**Comment by ryanidev** [comment]
If you go [here](https://idevicesinc.com/sweetblue/), and enter your email, you will be able to download a zip which contains some simple sample apps, one of them showing how to use the ota transaction.
