### ISSUE TITLE
startRssiPoll Not Working When BleDevice in BleDeviceState.DISCONNECTED.

### ISSUE THREAD

**Issue by lorenzowoodridge** [iDevicesInc/SweetBlue#416]
It is to my understanding that startRssiPoll can be called even when the BleDevice is in state BleDeviceState.DISCONNECTED because in the docs it says "TIP: You can call this method when the device is in any BleDeviceState, even BleDeviceState.DISCONNECTED." However when I try performing this poll when that device is in that state the callback is never called.

**Comment by lorenzowoodridge** [comment]
Great, that is what I had assumed! Any estimate on a time frame for this bug fix?

**Comment by lorenzowoodridge** [comment]
Just checking the status on this. Do you have an ETA?

**Comment by ryanidev** [comment]
This was fixed in an earlier version.
