### ISSUE TITLE
advertisement data not updated during scan

### ISSUE THREAD

**Issue by xmike** [iDevicesInc/SweetBlue#419]
the advertisment data of a particular device in a discovery event ("rediscover") is not updated, if data changes during scan. In this particular case I was observing the advertisement flags. The native scan record attached to the event is correct, though. If this is the intended behaviour, it should be noted in the documentation.

**Comment by ryanidev** [comment]
Actually, the advertisement data IS updated on scans. However, the advertising flags are not getting updated in certain scenarios. We'll get it fixed in the next release.

**Comment by ryanidev** [comment]
Fixed in 2.52.15
