### ISSUE TITLE
Mocking Bluetooth Devices

### ISSUE THREAD

**Issue by AlejandroHCruz** [iDevicesInc/SweetBlue#440]
Hi, is there any prefered way for mocking the Bluetooth communication with real devices?

Testing, overall, is quite complicated because the devices can drive apart, packages can be dropped and so on. There are many environmental factors in  real life that could affect the usage of a Bluetooth companion app. 

Thank you in advance for your advice.

**Comment by ryanidev** [comment]
This isn't something that v2 will support. V3 will have a unit test module you can use, but it requires a license to be purchased to get access.
