### ISSUE TITLE
How can i build the latest sweetblue library with gradle option

### ISSUE THREAD

**Issue by FahidDis** [iDevicesInc/SweetBlue#447]
With latest documentation there is no option to include library with gradle. I want to use library with gradle and not putting the library files in the project in it self.

Is there any way through which i can use this library using gradle instead of placing whole library in my project i don't want to increase the size of my app. Thanks

**Comment by ryanidev** [comment]
Just so you know, no matter how you include SweetBlue, it will be in your app. Just adding it as a maven dependency doesn't mean the code won't be on your apk (if it weren't then how would it even work?). Anyway, you can go to idevicesinc.com/sweetblue and fill in your email address. We will email you a link to download a zip file, which contains some sample projects, and a jar, and aar files to include in your project.
