### ISSUE TITLE
Automatic Reconnect clarification

### ISSUE THREAD

**Issue by barchard** [iDevicesInc/SweetBlue#450]
Hi,

I am following [this guide](https://github.com/iDevicesInc/SweetBlue/wiki/Reconnection) where I define a `DefaultReconnectFilter` to ask SweetBlue to please retry the connection for a previously connection device as follows:

```
    final BleManagerConfig.ReconnectFilter reconnectFilter = new BleNodeConfig.DefaultReconnectFilter() {
        @Override
        public Please onEvent(ReconnectEvent e) {
            Please please = Please.stopRetrying();
            if (devices.containsKey(e.macAddress())) {
                // If we've spent all of our time
                if (e.totalTimeReconnecting().gte(BleNodeConfig.DefaultReconnectFilter.LONG_TERM_TIMEOUT)) {
                    Timber.d("Scheduling retry of connection for " + e.macAddress());
                    // Retry to connect in 20 minutes.
                    please = Please.retryIn(Interval.mins(20));
                } else {
                    // Continue attempting with the current short or long term reconnect logic
                    please = Please.persist();
                }
            }
            return please;
        }
    };
```

Basically, I am trying to say, "if you timed out during the long term reconnect, please try again at a periodicity of 20min". I do not, however, see SweetBlue re-request connections after 20 minutes. Is this the best approach to accomplish this? Is `e.totalTimeReconnecting` the *overall* time reconnecting or just the time of the current connection attempt?

Thanks

**Comment by ryanidev** [comment]
I'd say to just use one of the default constructors for that class, where you define the amount of time to pause between each retry, and the timeout for each try.
```-java
DefaultReconnectFilter filter = new DefaultReconnectFilter(Interval.secs(1), Interval.mins(20), Interval.secs(5), Interval.mins(60));

// First parameter is the delay between tries for short term reconnect
// Second parameter is the delay between tries for long term
// Third is the overall timeout for short term
// Fourth is the overall timeout for long term
```

**Comment by barchard** [comment]
@ryanidev thanks, so if my understanding is correct, this will continuously retry any previously connected Bluetooth devices forever? If I'm no longer interested in retrying, how would I cancel this? It's not a standard use case, but I control what bluetooth devices users are using so I may exchange them for the user. In this case, the old BLE device should *really* be forgotten. Thanks

**Comment by ryanidev** [comment]
No it won't try forever. The overall timeout will stop the process. So if it did not get reconnected in the overall timeout period, it gives up (speaking of long term. If short term times out, it moves on to long term). But you can call disconnect() on the device before then, or even undiscover() if you want to completely clear it from the device cache in the library (if you do this, make sure you release any instance you're holding in the app to avoid issues later).
