### ISSUE TITLE
Script in samples repo for creating a new project.

### ISSUE THREAD

**Issue by dougkoellmer** [iDevicesInc/SweetBlue#98]
Should basically copy/paste hello_ble, find/replace the name in manifest/gradle files, and automatically add it to a config array so that it automatically gets its source copied from AS to eclipse folders like the rest of the projects.

**Comment by dougkoellmer** [comment]
Actually probably don't need to add the project to an array in configs.sh...can just do wildcard path matching like in the other scripts to copy/paste the code...same way we copy/paste latest sweetblue JARs into each project without knowing the project names.

**Comment by dougkoellmer** [comment]
Need to replace project name in (at least)...
 * Manifest file
 * Gradle file
 * Strings file
 * MyActivity.java file

Might be more.

**Comment by dougkoellmer** [comment]
Also have to change path from hello_ble/MyActivity.java to (e.g.) simple_write/MyActivity.java

**Comment by ryanidev** [comment]
Added. If no name is provided when calling the script, it will prompt for a name. It's best to keep names without spaces, as I'm sure that would cause issues right now.
