### ISSUE TITLE
Script for copying code from AS to eclipse also needs to copy res/

### ISSUE THREAD

**Issue by dougkoellmer** [iDevicesInc/SweetBlue#99]

**Comment by dougkoellmer** [comment]
Also copy AndroidManifest.xml probably...anything else that is "source" for compiling the actual project.

**Comment by ryanidev** [comment]
Looks like the script already was copying the manifest file.

I've updated the script to just look in the samples folder, and pull the directory names. The script will run through those directories to perform the android_studio -> eclipse copying.
